spring:
#  jmx:
#    enabled: false
  data:
    redis:
      host: 0.0.0.0
      database: 0
#      password: your-redis-password
      port: 6379

logging:
  file:
    name: "java-practice.log"
  level:
    root: DEBUG

