spring:
#  jmx:
#    enabled: false
  data:
    redis:
      host: 0.0.0.0
      database: 0
#      password: your-redis-password
      port: 6379
logging:
  level:
    root: info
# 不設定就沒有日誌file匯出
#logging:
#  file:
#    name: "java-practice.log"


some:
  key: 234

grpc:
  client:
    myGrpcService:
      address: "static://127.0.0.1:8081"  # gRPC 伺服器地址
      enableKeepAlive: true
      negotiationType: plaintext  # 禁用 TLS 顯示明文  （即不使用 HTTPS)