spring:
#  jmx:
#    enabled: false
  data:
    redis:
      host: 0.0.0.0
      database: 0
#      password: your-redis-password
      port: 6379
logging:
  level:
    root: info
# 不設定就沒有日誌file匯出
#logging:
#  file:
#    name: "java-practice.log"


some:
  key: 234